<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CIS2139VMRDS" name="com.avnet.emasia.webquote.entity.QtyCalTest" tests="23" failures="0" timestamp="11 Oct 2018 07:47:36 GMT" time="0.004" errors="2">
  <testcase name="calQtyIndicatorTest" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calMoqTest1" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest">
    <error type="java.lang.AssertionError" message="expected [1500] but found [1100]">
      <![CDATA[java.lang.AssertionError: expected [1500] but found [1100]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.avnet.emasia.webquote.entity.QtyCalTest.calMoqTest1(QtyCalTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </error>
  </testcase> <!-- calMoqTest1 -->
  <testcase name="calQuotedQtyTest24" time="0.001" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQuotedQtyTest2" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calMoqTest3" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="qtyIndicatorTest4" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="roundUpTest3" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="roundDownTest3" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="roundUpTest" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="roundDownTest2" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQuotedQtyTest3" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="roundUpTest2" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQtyIndicatorTest2" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQuotedQtyTest1" time="0.001" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQuotedQtyTest23" time="0.002" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQuotedQtyTest22" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQuotedQtyTest21" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="roundDownTest" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQuotedQtyTest11" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQuotedQtyTest12" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calQtyIndicatorTest6" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="qtyIndicatorTest3" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest"/>
  <testcase name="calMoqTest2" time="0.000" classname="com.avnet.emasia.webquote.entity.QtyCalTest">
    <error type="java.lang.AssertionError" message="expected [1800] but found [1100]">
      <![CDATA[java.lang.AssertionError: expected [1800] but found [1100]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.avnet.emasia.webquote.entity.QtyCalTest.calMoqTest2(QtyCalTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </error>
  </testcase> <!-- calMoqTest2 -->
</testsuite> <!-- com.avnet.emasia.webquote.entity.QtyCalTest -->
